package com.opnx.api.client.domain;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Status of a submitted order.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public enum OrderStatus {
  NONE,
  OPEN,
  PARTIAL_FILL,
  FILLED,
  CANCELED_BY_USER,
  CANCELED_BY_MARKET_ORDER_NOT_FULL_MATCHED,
  CANCELED_BY_MARKET_ORDER_NOTHING_MATCH,
  CANCELED_ALL_BY_IOC,
  CANCELED_PARTIAL_BY_IOC,
  CANCELED_BY_FOK,
  CANCELED_BY_MAKER_ONLY,
  REJECT_CANCEL_ORDER_ID_NOT_FOUND,
  REJECT_AMEND_ORDER_ID_NOT_FOUND,
  REJECT_DISPLAY_QUANTITY_LARGER_THAN_QUANTITY,
  REJECT_BUY_STOP_TRIGGER_LARGE_THAN_STOP_LIMITED,
  REJECT_SELL_STOP_TRIGGER_LESS_THAN_STOP_LIMITED,
  REJECT_UNKNOW_ORDER_ACTION,
  REJECT_QUANTITY_ZERO,
  REJECT_LIMITE_ORDER_WITH_MARKET_PRICE,
  CANCELED_ALL_BY_AUCTION,
  CANCELED_PARTIAL_BY_AUCTION,
  REJECT_AUCTION_SUPPORT_BUY_SELL_ONLY,
  CANCELED_BY_AMEND
}
